language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - travis_retry composer self-update

install:
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - travis_retry composer global require friendsofphp/php-cs-fixer "^2.0.0@dev"
    - travis_retry composer global require satooshi/php-coveralls "^1.0.0"
    - travis_retry composer update --no-interaction --prefer-source

before_script:
    - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then coverage="--coverage-xml"; fi
    - vendor/bin/codecept build

script:
    - php-cs-fixer fix --dry-run
    - vendor/bin/codecept run $coverage

after_script:
    - if [ $coverage != "" ]; then coveralls --verbose; fi
