language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

install:
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - composer global require friendsofphp/php-cs-fixer "^2.0.0@dev"
    - composer global require satooshi/php-coveralls "^1.0.0"
    - composer update --no-interaction

before_script:
    - if php -v | grep -q 'Xdebug'; then coverage="--coverage-xml"; fi
    - vendor/bin/codecept build

script:
    - php-cs-fixer fix --dry-run
    - vendor/bin/codecept run $coverage

after_success:
    - if [[ ! -z $coverage ]]; then coveralls; fi
